students_number: 1000
groups_number: 100
grades_number: 10000
subjects_number: 100
teachers_number: 100
surveys_number: 10000
max_consultations_per_teacher: 200

studies_number: 1000
teachings_number: 1000

surveys_date_range:
  min: "2020-01-01"
  max: "2023-12-31"

assessments_grade_range:
  min: 1
  max: 5

group_grade_range:
  min: 8
  max: 12

grades_range:
  min: 1
  max: 10

studies_year_range:
  min: 2020
  max: 2024

subjects_year_range:
  min: 2020
  max: 2024

consultations_per_teacher_range:
  min: 0
  max: 25

consultations_duration_range:
  min: 30
  max: 180

consultations_datetime_range:
  min: "2020-01-01T00:00:00"
  max: "2023-12-31T23:59:59"

faker_localization: 'pl_PL'

phone_number: "+48#########"

grade_titles:
  - wejściówka
  - kartkówka
  - test
  - aktywność
  - quiz
  - kolokwium
  - egzamin
  - zadanie domowe

specializations:
  - matematyczno-fizyczny
  - matematyczno-informatyczny
  - humanistyczny
  - biologiczno-chemiczny
  - fizyczno-informatyczne
  - artystyczny
  - geograficzny
  - dziennikarski
  - historyczny
  - językowo-turystyczny
  - menedżersko-ekonomiczny
  - psychologiczno-społeczny
  - społeczno-prawny
  - prawniczy
  - politechniczny
  - przyrodniczo-medyczny
  - medyczny
  - ekonomiczno-biznesowy
  - medialny
  - europejskiy
  - policyjno-mundurowy
  - artystyczno-teatralny
  - programistyczny
  - e-sportowy

subjects:
- język polski
- język obcy nowożytny
- drugi język obcy nowożytny
- muzyka
- plastyka
- historia
- wiedza o społeczeństwie
- przyroda
- geografia
- biologia
- chemia
- fizyka
- matematyka
- informatyka
- technika
- wychowanie fizyczne
- edukacja dla bezpieczeństwa
- wychowanie do życia w rodzinie
- etyka
- historia i teraźniejszość
- podstawy przedsiębiorczości
- edukacja dla bezpieczeństwa
- wychowanie do życia w rodzinie
- język łaciński i kultura antyczna

assessments_questions:
  - "Czy zajęcia były prowadzone w sposób zrozumiały?"
  - "Czy zajęcia były prowadzone w sposób interesujący?"
  - "Czy zajęcia były prowadzone w sposób przystosowany do poziomu grupy?"
  - "Czy zajęcia były prowadzone w sposób przystosowany do indywidualnych potrzeb ucznia?"
  - "Czy nauczyciel był przygotowany do zajęć?"
  - "Czy nauczyciel zachęcał do aktywnego uczestnictwa w zajęciach?"
  - "Czy nauczyciel zachowywał się w sposób profesjonalny?"
  - "Czy nauczyciel był pomocny w rozwiązywaniu problemów?"
  - "Czy nauczyciel był dostępny poza zajęciami?"
  - "Czy nauczyciel był pomocny w przygotowaniu do egzaminów?"
